import skills

PIXEL_PER_METER = (50.0 / 0.3)
def get_speed_pps(RUN_SPEED_KMPH):
    RUN_SPEED_MPM = (RUN_SPEED_KMPH * 1000.0 / 60)
    RUN_SPEED_MPS = (RUN_SPEED_MPM / 60.0)
    RUN_SPEED_PPS = (RUN_SPEED_MPS * PIXEL_PER_METER)

    return RUN_SPEED_PPS

key_Idle, key_Run, key_Sturn, key_Skill, key_Speed, key_Cool_Time, key_Skill_Application_Time, key_Skill_Text = range(8)
VERY_SLOW, SLOW, NORMAL, FAST, VERY_FAST = get_speed_pps(1), get_speed_pps(1.5), get_speed_pps(2.0), get_speed_pps(2.5), get_speed_pps(3)
among, dog, ghost, hulk, human, icarus, kirby, ninja, patrick_star, pikachu, sonic, spiderman, turtle, witch, zombie = range(15)

characters = {
    patrick_star: {
        "name": "PatrickStar",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 7, "bottom": 120, "width": 30, "height": 50},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 9, "bottom": 60, "width": 32, "height": 50},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 4, "bottom": 0, "width": 40, "height": 50},
        key_Skill: None,
        key_Speed: NORMAL,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "",
    }, sonic: {
        "name": "sonic",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 174, "width": 30, "height": 40},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 8, "bottom": 126, "width": 42, "height": 38},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 2, "bottom": 71, "width": 40, "height": 45},
        key_Skill: {"ActionPerTime": 5, "FramePerAction": 6, "bottom": 0, "width": 32, "height": 27},
        key_Speed: FAST,
        key_Cool_Time: 15,
        key_Skill_Application_Time: 5,
        key_Skill_Text: "5초간 이동 속도가 증가 한다",
    }, hulk: {
        "name": "hulk",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 3, "bottom": 200, "width": 60, "height": 90},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 6, "bottom": 100, "width": 90, "height": 90},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 5, "bottom": 0, "width": 100, "height": 90},
        key_Skill: None,
        key_Speed: SLOW,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 3,
        key_Skill_Text: "3초간 해로운 효과를 받지 않습니다.",
    }, kirby: {
        "name": "kirby",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 6, "bottom": 85, "width": 50, "height": 40},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 45, "width": 50, "height": 40},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 4, "bottom": 0, "width": 50, "height": 45},
        key_Skill: None,
        key_Speed: FAST,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "해로운 효과를 제거 한다",
    }, turtle: {
        "name": "turtle",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 5, "bottom": 56, "width": 70, "height": 47},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 6, "bottom": 0, "width": 70, "height": 46},
        key_Sturn: None,
        key_Skill: None,
        key_Speed: VERY_SLOW,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "",
    }, ghost: {
        "name": "ghost",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 8, "bottom": 65, "width": 75, "height": 63},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 6, "bottom": 0, "width": 75, "height": 55},
        key_Sturn: None,
        key_Skill: None,
        key_Speed: FAST,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "",
    }, pikachu: {
        "name": "pikachu",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 85, "width": 60, "height": 45},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 50, "width": 60, "height": 35},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 3, "bottom": 0, "width": 60, "height": 50},
        key_Skill: None,
        key_Speed: NORMAL,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "",
    }, among: {
        "name": "among",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 1, "bottom": 110, "width": 30, "height": 25},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 75, "width": 30, "height": 25},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 4, "bottom": 35, "width": 30, "height": 30},
        key_Skill: {"ActionPerTime": 3, "FramePerAction": 4, "bottom": 0, "width": 30, "height": 25},
        key_Speed: NORMAL,
        key_Cool_Time: 10,
        key_Skill_Application_Time: 3,
        key_Skill_Text: "3초간 이동 속도가 증가 한다",
    }, dog: {
        "name": "dog",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 2, "bottom": 150, "width": 100, "height": 45},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 7, "bottom": 85, "width": 100, "height": 65},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 6, "bottom": 0, "width": 100, "height": 85},
        key_Skill: None,
        key_Speed: FAST,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "",
    }, human: {
        "name": "human",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 1, "bottom": 158, "width": 38, "height": 42},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 108, "width": 38, "height": 40},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 2, "bottom": 52, "width": 38, "height": 46},
        key_Skill: {"ActionPerTime": 0.5, "FramePerAction": 2, "bottom": 0, "width": 38, "height": 42},
        key_Speed: NORMAL,
        key_Cool_Time: 10,
        key_Skill_Application_Time: 0.5,
        key_Skill_Text: "수리검을 던져 적을 스턴 상태로 만든다.",
    }, icarus: {
        "name": "icarus",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 204, "width": 65, "height": 60},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 6, "bottom": 144, "width": 65, "height": 60},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 8, "bottom": 84, "width": 65, "height": 60},
        key_Skill: {"ActionPerTime": 1.0, "FramePerAction": 4, "bottom": 24, "width": 65, "height": 60},
        key_Speed: VERY_FAST,
        key_Cool_Time: 10,
        key_Skill_Application_Time: 1.0,
        key_Skill_Text: "불을 발사해 적을 스턴 상태로 만든다.",
    }, ninja: {
        "name": "ninja",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 210, "width": 60, "height": 75},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 6, "bottom": 145, "width": 60, "height": 65},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 4, "bottom": 70, "width": 80, "height": 75},
        key_Skill: {"ActionPerTime": 0.8, "FramePerAction": 7, "bottom": 0, "width": 60, "height": 70},
        key_Speed: NORMAL,
        key_Cool_Time: 120,
        key_Skill_Application_Time: 2,
        key_Skill_Text: "플레이어가 앞으로 순간 이동합니다",
    }, witch: {
        "name": "witch",
        key_Idle: {"ActionPerTime": 1, "FramePerAction": 5, "bottom": 305, "width": 100, "height": 95},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 2, "bottom": 205, "width": 100, "height": 100},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 5, "bottom": 120, "width": 110, "height": 85},
        key_Skill: {"ActionPerTime": 0.8, "FramePerAction": 4, "bottom": 0, "width": 100, "height": 120},
        key_Speed: FAST,
        key_Cool_Time: 10.0,
        key_Skill_Application_Time: 5,
        key_Skill_Text: "모든 플레이어의 이동 속도를 감소 시킨다.",
    }, zombie: {
        "name": "zombie",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 4, "bottom": 145, "width": 90, "height": 75},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 5, "bottom": 70, "width": 90, "height": 75},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 8, "bottom": 0, "width": 90, "height": 70},
        key_Skill: None,
        key_Speed: VERY_SLOW,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "상대에게 붙으면 상대의 이동 속도를 감소 시킨다.",
    }, spiderman: {
        "name": "spiderman",
        key_Idle: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 3, "bottom": 110, "width": 70, "height": 70},
        key_Run: {"ActionPerTime": 1.0 / 0.5, "FramePerAction": 8, "bottom": 50, "width": 70, "height": 60},
        key_Sturn: {"ActionPerTime": 2, "FramePerAction": 3, "bottom": 0, "width": 50, "height": 50},
        key_Skill: None,
        key_Speed: FAST,
        key_Cool_Time: 0,
        key_Skill_Application_Time: 0,
        key_Skill_Text: "",
    }, 
}

